sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run compile
- npm run test
- npm run lint
before_deploy:
- pip install --user awscli
- npm run deploy
deploy:
  - provider: script
    skip_cleanup: true
    script: .aws/deploy
    access_key_id: AKIAIF35EA6NPCKM7MXA
    on:
      branch: master
      repo: nobt-io/frontend
  - provider: script
    skip_cleanup: true
    script: .sentry/upload-sourcemaps
    on:
      branch: master
      repo: nobt-io/frontend
