sudo: false
language: node_js
node_js:
  - '6'

env:
  global:
  - ENCRYPTION_LABEL: "b1262a2766a6"
  - COMMIT_AUTHOR_EMAIL: "bot@nobt.io"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
#  - npm run lint
  - npm run test
  - npm run deploy

after_success:
  - ".sentry/upload-sourcemaps"
  - ".github/deploy-to-gh-pages"